<?php
/**
 * TL_ROOT/system/modules/inserttags/languages/ja/modules.php 
 * 
 * Contao extension: inserttags 1.9.0 stable 
 * Japanese translation file 
 * 
 * Copyright : © 2008-2013 terminal42 gmbh 
 * License   : LGPL 
 * Author    : terminal42 gmbh (terminal42), http://www.terminal42.ch/ 
 * Translator: Takahiro Kambe (taca), http://www.contaocms.jp/ 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['inserttags']['0'] = "挿入タグ";
$GLOBALS['TL_LANG']['MOD']['inserttags']['1'] = "このモジュールは独自の挿入タグを作成して、定義した内容と置き換えをできるようにします。電話番号のような、同じ内容を複数のページに含めたい場合にたいへん役立ちます。電話番号を変えた場合でも一度変更するだけで済み、ページの更新漏れが起きることはありません。";
 
?>
