<?php
/**
 * TL_ROOT/system/modules/inserttags/languages/ja/tl_inserttags.php 
 * 
 * Contao extension: inserttags 1.9.0 stable 
 * Japanese translation file 
 * 
 * Copyright : © 2008-2013 terminal42 gmbh 
 * License   : LGPL 
 * Author    : terminal42 gmbh (terminal42), http://www.terminal42.ch/ 
 * Translator: Takahiro Kambe (taca), http://www.contaocms.jp/ 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_inserttags']['tag']['0'] = "挿入タグ";
$GLOBALS['TL_LANG']['tl_inserttags']['tag']['1'] = "挿入タグを入力してください。<br />どのコンテンツ要素でも、このタグを{{custom::your-tag}}として使用できます。";
$GLOBALS['TL_LANG']['tl_inserttags']['replacement']['0'] = "置き換える内容";
$GLOBALS['TL_LANG']['tl_inserttags']['replacement']['1'] = "挿入タグと置き換えたい内容を入力してください。";
$GLOBALS['TL_LANG']['tl_inserttags']['disableRTE']['0'] = "TinyMCEを使用しない";
$GLOBALS['TL_LANG']['tl_inserttags']['disableRTE']['1'] = "リッチテキストエディタTinyMCEを使用したくない場合にチェックしてください。";
$GLOBALS['TL_LANG']['tl_inserttags']['description']['0'] = "説明";
$GLOBALS['TL_LANG']['tl_inserttags']['description']['1'] = "同じタグを相互に区別するために、この挿入タグの説明を入力できます。";
$GLOBALS['TL_LANG']['tl_inserttags']['timing']['0'] = "日時指定";
$GLOBALS['TL_LANG']['tl_inserttags']['timing']['1'] = "このタグを開始と終了の日や時刻を指定できます。異なる日時で複数の同じ名前のタグを作成して、日時によって異なる内容と置き換えができます。";
$GLOBALS['TL_LANG']['tl_inserttags']['start_date']['0'] = "開始日";
$GLOBALS['TL_LANG']['tl_inserttags']['start_date']['1'] = "このタグを開始する日(日/月/年)を入力してください。<br />入力欄を空にして、値を指定しないことができます。(例: 年)";
$GLOBALS['TL_LANG']['tl_inserttags']['start_time']['0'] = "開始時刻";
$GLOBALS['TL_LANG']['tl_inserttags']['start_time']['1'] = "このタグを開始する時刻(時/分)を入力してください。";
$GLOBALS['TL_LANG']['tl_inserttags']['end_date']['0'] = "終了日";
$GLOBALS['TL_LANG']['tl_inserttags']['end_date']['1'] = "このタグを終了する日(日/月/年)を入力してください。";
$GLOBALS['TL_LANG']['tl_inserttags']['end_time']['0'] = "終了時刻";
$GLOBALS['TL_LANG']['tl_inserttags']['end_time']['1'] = "このタグを終了する時刻(時/分)を入力してください。";
$GLOBALS['TL_LANG']['tl_inserttags']['mode']['0'] = "挿入タグの適用先";
$GLOBALS['TL_LANG']['tl_inserttags']['mode']['1'] = "挿入タグをバックエンドまたはフロントエンドに適用するか選択してください。";
$GLOBALS['TL_LANG']['tl_inserttags']['cacheOutput']['0'] = "出力をキャッシュ";
$GLOBALS['TL_LANG']['tl_inserttags']['cacheOutput']['1'] = "Contaoがページをキャッシュする前に挿入タグを適用したい場合に選択してください。";
$GLOBALS['TL_LANG']['tl_inserttags']['useCondition']['0'] = "条件";
$GLOBALS['TL_LANG']['tl_inserttags']['useCondition']['1'] = "特定の条件で挿入タグを使用したい場合に選択してください。";
$GLOBALS['TL_LANG']['tl_inserttags']['conditionType']['0'] = "問い合わせのタイプ";
$GLOBALS['TL_LANG']['tl_inserttags']['conditionType']['1'] = "データベースを選択した場合に、有効なSQLの問い合わせを入力してください。最初の列の最初のフィールドが置き換える内容となります。問い合わせに挿入タグを使用できます。";
$GLOBALS['TL_LANG']['tl_inserttags']['conditionQuery']['0'] = "問い合わせ";
$GLOBALS['TL_LANG']['tl_inserttags']['conditionQuery']['1'] = "問い合わせを入力してください。例えば、Contaoの挿入タグとすることもできます。";
$GLOBALS['TL_LANG']['tl_inserttags']['conditionFormula']['0'] = "条件式";
$GLOBALS['TL_LANG']['tl_inserttags']['conditionFormula']['1'] = "値と比較する条件式を選択してください。";
$GLOBALS['TL_LANG']['tl_inserttags']['conditionValue']['0'] = "値";
$GLOBALS['TL_LANG']['tl_inserttags']['conditionValue']['1'] = "問い合わせが一致する値を入力してください。";
$GLOBALS['TL_LANG']['tl_inserttags']['limitpages']['0'] = "ページを制限";
$GLOBALS['TL_LANG']['tl_inserttags']['limitpages']['1'] = "挿入タグを特定のページに制限したい場合に選択してください。";
$GLOBALS['TL_LANG']['tl_inserttags']['pages']['0'] = "ページ";
$GLOBALS['TL_LANG']['tl_inserttags']['pages']['1'] = "この挿入タグを適用したいページを選択してください。";
$GLOBALS['TL_LANG']['tl_inserttags']['includesubpages']['0'] = "下位のページも対象";
$GLOBALS['TL_LANG']['tl_inserttags']['includesubpages']['1'] = "選択したページの下位のページにも挿入タグを適用したい場合に選択してください。";
$GLOBALS['TL_LANG']['tl_inserttags']['limitLanguages']['0'] = "言語を制限";
$GLOBALS['TL_LANG']['tl_inserttags']['limitLanguages']['1'] = "この挿入タグを特定の言語に制限したい場合に選択してください。";
$GLOBALS['TL_LANG']['tl_inserttags']['languages']['0'] = "言語";
$GLOBALS['TL_LANG']['tl_inserttags']['languages']['1'] = "この挿入タグを適用したい言語を選択してください。";
$GLOBALS['TL_LANG']['tl_inserttags']['useCounter']['0'] = "カウンターを使用";
$GLOBALS['TL_LANG']['tl_inserttags']['useCounter']['1'] = "ある呼び出し回数の後だけ、この挿入タグを標示するカウンターを追加します。";
$GLOBALS['TL_LANG']['tl_inserttags']['counterValue']['0'] = "現在の値";
$GLOBALS['TL_LANG']['tl_inserttags']['counterValue']['1'] = "これは現在のカウンターの値です。これは最初に値を設定しなければなりません。そして、この挿入タグを使用するたびに1つずつ減って行きます。";
$GLOBALS['TL_LANG']['tl_inserttags']['counterDefault']['0'] = "初期値";
$GLOBALS['TL_LANG']['tl_inserttags']['counterDefault']['1'] = "初期値を入力してください。カウンターの繰り返しを有効にしている場合、値が0になるとこの値にカウンターは戻ります。";
$GLOBALS['TL_LANG']['tl_inserttags']['counterRepeat']['0'] = "カウンターの繰り返し";
$GLOBALS['TL_LANG']['tl_inserttags']['counterRepeat']['1'] = "このカウンターを繰り返したいときに選択してください。";
$GLOBALS['TL_LANG']['tl_inserttags']['protected']['0'] = "挿入タグの保護";
$GLOBALS['TL_LANG']['tl_inserttags']['protected']['1'] = "特定のメンバーグループに挿入タグを標示します。";
$GLOBALS['TL_LANG']['tl_inserttags']['groups']['0'] = "許可するメンバーグループ";
$GLOBALS['TL_LANG']['tl_inserttags']['groups']['1'] = "これらのグループに挿入タグを表示します。";
$GLOBALS['TL_LANG']['tl_inserttags']['guests']['0'] = "ゲストだけに表示";
$GLOBALS['TL_LANG']['tl_inserttags']['guests']['1'] = "ログインしているメンバーに挿入タグを表示しません。";
$GLOBALS['TL_LANG']['tl_inserttags']['eq'] = "等しい";
$GLOBALS['TL_LANG']['tl_inserttags']['neq'] = "等しくない";
$GLOBALS['TL_LANG']['tl_inserttags']['lt'] = "より小さい";
$GLOBALS['TL_LANG']['tl_inserttags']['gt'] = "より大きい";
$GLOBALS['TL_LANG']['tl_inserttags']['elt'] = "等しいかより小さい";
$GLOBALS['TL_LANG']['tl_inserttags']['egt'] = "等しいかより大きい";
$GLOBALS['TL_LANG']['tl_inserttags']['starts'] = "開始の文字列(大文字小文字を区別しない)";
$GLOBALS['TL_LANG']['tl_inserttags']['ends'] = "終了の文字列(大文字小文字を区別しない)";
$GLOBALS['TL_LANG']['tl_inserttags']['contains'] = "含める文字列(大文字小文字を区別しない)";
$GLOBALS['TL_LANG']['tl_inserttags']['istarts'] = "開始の文字列(大文字小文字を区別)";
$GLOBALS['TL_LANG']['tl_inserttags']['iends'] = "終了の文字列(大文字小文字を区別)";
$GLOBALS['TL_LANG']['tl_inserttags']['icontains'] = "含める文字列(大文字小文字を区別)";
$GLOBALS['TL_LANG']['tl_inserttags']['fe'] = "フロントエンド";
$GLOBALS['TL_LANG']['tl_inserttags']['be'] = "バックエンド";
$GLOBALS['TL_LANG']['tl_inserttags']['text'] = "テキスト";
$GLOBALS['TL_LANG']['tl_inserttags']['database'] = "データベース";
$GLOBALS['TL_LANG']['tl_inserttags']['new']['0'] = "タグを作成";
$GLOBALS['TL_LANG']['tl_inserttags']['new']['1'] = "新しく挿入タグを作成";
$GLOBALS['TL_LANG']['tl_inserttags']['edit']['0'] = "タグを変更";
$GLOBALS['TL_LANG']['tl_inserttags']['edit']['1'] = "ID %sの挿入タグを変更";
$GLOBALS['TL_LANG']['tl_inserttags']['copy']['0'] = "タグを複製";
$GLOBALS['TL_LANG']['tl_inserttags']['copy']['1'] = "ID %sの挿入タグを複製";
$GLOBALS['TL_LANG']['tl_inserttags']['cut']['0'] = "タグを移動";
$GLOBALS['TL_LANG']['tl_inserttags']['cut']['1'] = "ID %sの挿入タグを移動";
$GLOBALS['TL_LANG']['tl_inserttags']['delete']['0'] = "タグを削除";
$GLOBALS['TL_LANG']['tl_inserttags']['delete']['1'] = "ID %sの挿入タグを削除";
$GLOBALS['TL_LANG']['tl_inserttags']['show']['0'] = "タグの詳細";
$GLOBALS['TL_LANG']['tl_inserttags']['show']['1'] = "ID %sの挿入タグの詳細を標示";
$GLOBALS['TL_LANG']['tl_inserttags']['pasteafter']['0'] = "後に貼付け";
$GLOBALS['TL_LANG']['tl_inserttags']['pasteafter']['1'] = "ID %sの挿入タグの後に貼付け";
$GLOBALS['TL_LANG']['tl_inserttags']['pasteinto']['0'] = "中に貼付け";
$GLOBALS['TL_LANG']['tl_inserttags']['pasteinto']['1'] = "先頭に貼付け";
$GLOBALS['TL_LANG']['tl_inserttags']['tag_legend'] = "タグと置き換える内容";
$GLOBALS['TL_LANG']['tl_inserttags']['limit_legend'] = "制限";
$GLOBALS['TL_LANG']['tl_inserttags']['advanced_legend'] = "高度なオプション";
$GLOBALS['TL_LANG']['tl_inserttags']['expert_legend'] = "専門的な設定";
 
?>
